"""Security response headers + CSRF cookie middleware.

Adds security-related HTTP headers to every response:
- X-Frame-Options: DENY (prevents clickjacking)
- X-Content-Type-Options: nosniff (prevents MIME sniffing)
- Referrer-Policy: strict-origin-when-cross-origin (controls referrer leakage)
- Content-Security-Policy: restricts resource sources to self + Bootstrap CDN

Also sets the CSRF cookie on GET responses (token lifecycle managed here
so individual route handlers don't need to touch cookie management).
"""

from __future__ import annotations

from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
from starlette.requests import Request
from starlette.responses import Response

from ..security.csrf import generate_token, set_cookie


class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    """Middleware that adds security headers and CSRF cookie to every response.

    Applied as the outermost middleware so headers are present on all
    responses including those generated by inner middleware layers.
    CSRF cookie is set on GET/HEAD responses so that form-rendering pages
    automatically receive a valid token.
    """

    async def dispatch(
        self,
        request: Request,
        call_next: RequestResponseEndpoint,
    ) -> Response:
        response = await call_next(request)
        response.headers["X-Frame-Options"] = "DENY"
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
        response.headers["Content-Security-Policy"] = (
            "default-src 'self'; "
            "script-src 'self' https://cdn.jsdelivr.net; "
            "style-src 'self' https://cdn.jsdelivr.net; "
            "img-src 'self' data:; "
            "font-src https://cdn.jsdelivr.net; "
            "form-action 'self'; "
            "base-uri 'self';"
        )
        # Set CSRF cookie on safe methods (GET/HEAD) if not already present
        if request.method in ("GET", "HEAD"):
            if not request.cookies.get("csrf_token"):
                token = generate_token()
                set_cookie(response, token)
        return response
